### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 1aozhang** [Rabithua/memos_wmp#74]
Memos Version: v0.24.0

平台：阿里云

部署：

1）Nginx Proxy Manager通过docker部署，开放80和443端口，接收请求并转发到后台服务。

```
services:
  app:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-log:/tmp/letsencrypt-log
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:81
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks: {}
```

2）Memos通过docker部署，不暴露5230接口。
Memos容器接入NPM容器网络，通过NPM配置vhost，通过域名访问请求可经过docker内部网络转发到Memos容器内应用的5230端口。

```
services:
  memos:
    container_name: memos
    volumes:
      - /srv/docker/memos/:/var/opt/memos
    image: neosmemo/memos:stable
    networks:
      - nginx-proxy-manager_default
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null
        http://localhost:5230 &> /dev/null || exit 1
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
networks:
  nginx-proxy-manager_default:
    external: true
```

3) 开发工具中调试，无法登录

app.js只修改了globalData.url

```
  globalData: {
    // 【一般需要修改为 false】是否开启微信自动登录，需要手动配置后端接口以及开启小程序认证权限才能生效，否则会报错。
    ifWechatLogin: false,
    // 注意域名后面不要带斜杠
    url: 'https://xxx.xxx.xxx',
    // 搭配ifWechatLogin使用
    backendUrl: '',
    top_btn: wx.getMenuButtonBoundingClientRect()
  },
```

加载时报错如下：
```
[渲染层错误] Mon Mar 10 2025 21:06:10 GMT+0800 (中国标准时间) 社区相关帖子推荐
 原报错信息: Uncaught ReferenceError: Trace is not defined
    at http://127.0.0.1:15511/__pageframe__/__dev__/WARemoteDebugForLib3.js?t=wechat&s=1741609064073:1:253701
    at http://127.0.0.1:15511/__pageframe__/__dev__/WARemoteDebugForLib3.js?t=wechat&s=1741609064073:1:254052
    at http://127.0.0.1:15511/__pageframe__/__dev__/WARemoteDebugForLib3.js?t=wechat&s=1741609064073:1:254056
    at http://127.0.0.1:15511/__pageframe__/__dev__/WARemoteDebugForLib3.js?t=wechat&s=1741609064073:1:254060 
 基础库已知问题，可使用大于等于 3.0.2 的基础库版本
 关于上述报错，点击查看更多信息：(env: Windows,mp,1.06.2412050; lib: 2.25.4)
[渲染层错误] ReferenceError: SystemError (webviewScriptError)
Trace is not defined(env: Windows,mp,1.06.2412050; lib: 2.25.4)
```
以及
```
[渲染层网络层错误] Failed to load font https://img.rabithua.club/%E9%BA%A6%E9%BB%98/SmileySans-Oblique.ttf
net::ERR_CACHE_MISS 
(env: Windows,mp,1.06.2412050; lib: 2.25.4)
```
以及
```
GET https://xxx.xxx.xxx/api/v1/status 404 (Not Found)(env: Windows,mp,1.06.2412050; lib: 2.25.4)
```
尝试登录后
```
POST https://xxx.xxx.xxx/api/v1/auth/signin 400 (Bad Request)(env: Windows,mp,1.06.2412050; lib: 2.25.4)
```

已将域名隐去。

Memos本身服务是可以访问的。
网页版和通过MoeMemos客户端都可以正常访问和使用。
域名已经过备案。
不过证书是用的certbot配置的免费证书。但应该不造成问题。

是由于Memos本身版本的问题么？
